# Generated by Django 4.1.7 on 2023-03-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_editora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='nome',
        ),
    ]
